import 'package:flutter/material.dart';


class AllahinIsimleri extends StatefulWidget {
  @override
  _AllahinIsimleriState createState() => _AllahinIsimleriState();
}

class _AllahinIsimleriState extends State<AllahinIsimleri> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          SingleChildScrollView(
            child: Text('AR-RAHMAAN\nAR-RAHEEM\nAL-MALIK\nAL-QUDDUS\nAS-SALAM\nAL-MUMIN\nAL-MUHAYMIN\nAL-AZEEZ\nAL-JABBAR\nAL-MUTAKABBIR\nAL-KHAALIQ\nAL-BAARI\nAL-MUSAWWIR\nAL-GHAFFAR\nAL-QAHHAR\nAL-WAHHAAB\nAR-RAZZAAQ\nAL-FATTAAH\nAL-ALEEM\nAL-QAABID\nAL-BAASIT\nAL-KHAAFIDH\nAR-RAAFI\nAL-MUIZZ\nAL-MUZIL\nAS-SAMEE\nAL-BASEER\nAL-HAKAM\nAL-ADL\nAL-LATEEF\nAL-KHABEER\nAL-HALEEM\nAL-ATHEEM\nAL-GHAFOOR\nASH-SHAKOOR\nAL-ALEE\nAL-KABEER\nAL-HAFEEDH\nAL-MUQEET\nAL-HASEEB\nAL-JALEEL\nAL-KAREEM\nAR-RAQEEB\nAL-MUJEEB\nAL-WAASI\nAL-HAKEEM\nAL-WADOOD\nAL-MAJEED\nAL-BAITH\nASH-SHAHEED\nAL-HAQQ\nAL-WAKEEL\nAL-QAWIYY\nAL-MATEEN\nAL-WALIYY\nAL-HAMEED\nAL-MUHSEE\nAL-MUBDI\nAL-MUID\nAL-MUHYEE\nAL-MUMEET\nAL-HAYY\nAL-QAYYOOM\nAL-WAAJID\nAL-MAAJID\nAL-WAAHID\nAL-AHAD\nAS-SAMAD\nAL-QADIR\nAL-MUQTADIR\nAL-MUQADDIM\nAL-MUAKHKHIR\nAL-AWWAL\nAL-AAKHIR\nAZ-DHAAHIR\nAL-BAATIN\nAL-WAALI\nAL-MUTAALI\nAL-BARR\nAT-TAWWAB\nAL-MUNTAQIM\nAL-AFUWW\nAR-RAOOF\nMAALIK-UL-MULK\nDHUL-JALAALI WAL-IKRAAM\nAL-MUQSIT\nAL-JAAMI\nAL-GHANIYY\nAL-MUGHNI\nAL-MANI\nAD-DHARR\nAN-NAFI\nAN-NUR\nAL-HAADI\nAL-BADEE\nAL-BAAQI\nAL-WAARITH\nAR-RASHEED\nAS-SABOOR'),
          ),
        ],
      ),
    );
  }
}
